// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenToWork.Models.Context;

#nullable disable

namespace OpenToWork.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("WizardCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("WizardStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Identification");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("WizardCompleted", "IsDeleted");

                    b.ToTable("PT_Candidates", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_SkillId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_SkillId", "IsDeleted");

                    b.HasIndex("PT_CandidateId", "PT_SkillId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_CandidateSkills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("Name", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_Companies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsDeleted");

                    b.HasIndex("Name", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_Skills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTempVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt", "IsDeleted");

                    b.HasIndex("IsPublished", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted");

                    b.ToTable("PT_TempVacancies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsRevoked", "IsDeleted");

                    b.ToTable("SC_RefreshTokens", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PrimaryRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("GoogleId IS NOT NULL AND IsDeleted = 0");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("SC_Users", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId", "IsTrusted");

                    b.HasIndex("SCUserId", "DeviceHash", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SC_UserDevices", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("SCUserId", "Role", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SC_UserRoles", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYUserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("es");

                    b.Property<int?>("PreferredRole")
                        .HasColumnType("int");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("navy");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SY_UserPreferences", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYWizardStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StepNumber", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("Order", "Phase", "IsDeleted");

                    b.ToTable("SY_WizardSteps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("73b9d550-e578-484d-a666-7517c55d33a1"),
                            CreatedAt = new DateTime(2026, 8, 12, 3, 5, 30, 532, DateTimeKind.Utc).AddTicks(967),
                            Description = "Tell us about yourself",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 1,
                            Phase = 1,
                            StepName = "PersonalData",
                            StepNumber = 1,
                            StepTitle = "Personal Data"
                        },
                        new
                        {
                            Id = new Guid("12dccc0e-4f0d-452c-bbd3-3c10d041646a"),
                            CreatedAt = new DateTime(2026, 8, 12, 3, 5, 30, 532, DateTimeKind.Utc).AddTicks(976),
                            Description = "Where are you located?",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 2,
                            Phase = 1,
                            StepName = "Location",
                            StepNumber = 2,
                            StepTitle = "Location"
                        },
                        new
                        {
                            Id = new Guid("6ed148be-adbb-4d53-a652-3f220a79ebc6"),
                            CreatedAt = new DateTime(2026, 8, 12, 3, 5, 30, 532, DateTimeKind.Utc).AddTicks(990),
                            Description = "Your professional information",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 3,
                            Phase = 1,
                            StepName = "ProfessionalProfile",
                            StepNumber = 3,
                            StepTitle = "Professional Profile"
                        },
                        new
                        {
                            Id = new Guid("fb535ba9-4da7-44d3-b861-31b84cc7cbf2"),
                            CreatedAt = new DateTime(2026, 8, 12, 3, 5, 30, 532, DateTimeKind.Utc).AddTicks(992),
                            Description = "Select your skills",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 4,
                            Phase = 1,
                            StepName = "Skills",
                            StepNumber = 4,
                            StepTitle = "Skills"
                        },
                        new
                        {
                            Id = new Guid("86419f0a-c00d-4404-85b1-59f0d68b4673"),
                            CreatedAt = new DateTime(2026, 8, 12, 3, 5, 30, 532, DateTimeKind.Utc).AddTicks(994),
                            Description = "Choose your preference",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 5,
                            Phase = 1,
                            StepName = "Preferences",
                            StepNumber = 5,
                            StepTitle = "What do you want to do?"
                        },
                        new
                        {
                            Id = new Guid("e1b54569-71d6-430d-86e9-8f151f377777"),
                            CreatedAt = new DateTime(2026, 8, 12, 3, 5, 30, 532, DateTimeKind.Utc).AddTicks(996),
                            Description = "Verify your data is correct",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 6,
                            Phase = 1,
                            StepName = "Confirmation",
                            StepNumber = 6,
                            StepTitle = "Review and Confirm"
                        });
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("Candidate")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCandidate", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateSkill", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTSkill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("PT_SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("Company")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCompany", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTempVacancy", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("TempVacancies")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCRefreshToken", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserDevice", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserRole", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYUserPreference", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("OpenToWork.Models.Entities.SYUserPreference", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTSkill", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUser", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Company");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TempVacancies");

                    b.Navigation("UserDevices");

                    b.Navigation("UserPreference");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
