// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenToWork.Models.Context;

#nullable disable

namespace OpenToWork.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenToWork.Models.Entities.PTApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ApplicationSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AvailableFromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("ExpectedSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_VacancyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateId", "PT_VacancyId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("PT_CandidateId", "Status", "IsDeleted");

                    b.HasIndex("PT_VacancyId", "Status", "IsDeleted");

                    b.ToTable("PT_Applications", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("Availability")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProfilePublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("WizardCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("WizardStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("WorkAuthorization")
                        .HasColumnType("int");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identification");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("WizardCompleted", "IsDeleted");

                    b.ToTable("PT_Candidates", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateId", "IsDeleted");

                    b.ToTable("PT_CandidateCertifications", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateId", "IsDeleted");

                    b.ToTable("PT_CandidateEducations", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrentJob")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName", "IsDeleted");

                    b.HasIndex("PT_CandidateId", "IsDeleted");

                    b.ToTable("PT_CandidateExperiences", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_SkillId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_SkillId", "IsDeleted");

                    b.HasIndex("PT_CandidateId", "PT_SkillId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_CandidateSkills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("Name", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_Companies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsDeleted");

                    b.HasIndex("Name", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_Skills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTempVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("EnglishLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt", "IsDeleted");

                    b.HasIndex("IsPublished", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted");

                    b.ToTable("PT_TempVacancies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("EnglishLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PT_CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("ViewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WorkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PT_CompanyId", "IsDeleted");

                    b.HasIndex("Status", "IsDeleted");

                    b.HasIndex("Category", "Status", "IsDeleted");

                    b.HasIndex("Location", "Status", "IsDeleted");

                    b.HasIndex("WorkMode", "Status", "IsDeleted");

                    b.ToTable("PT_Vacancies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("MinProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("PT_SkillId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_VacancyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_SkillId", "IsDeleted");

                    b.HasIndex("PT_VacancyId", "PT_SkillId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_VacancySkills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsRevoked", "IsDeleted");

                    b.ToTable("SC_RefreshTokens", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PrimaryRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("GoogleId IS NOT NULL AND IsDeleted = 0");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("SC_Users", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId", "IsTrusted");

                    b.HasIndex("SCUserId", "DeviceHash", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SC_UserDevices", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("SCUserId", "Role", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SC_UserRoles", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYUserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("es");

                    b.Property<int?>("PreferredRole")
                        .HasColumnType("int");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("navy");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SY_UserPreferences", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYWizardStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StepNumber", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("Order", "Phase", "IsDeleted");

                    b.ToTable("SY_WizardSteps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("68d9758f-2843-4c18-be66-d643feb5f7e7"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9559),
                            Description = "Tell us about yourself",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 1,
                            Phase = 1,
                            StepName = "PersonalData",
                            StepNumber = 1,
                            StepTitle = "Personal Data"
                        },
                        new
                        {
                            Id = new Guid("38db2517-920a-4874-afe3-84f1467355e0"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9566),
                            Description = "Where are you located?",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 2,
                            Phase = 1,
                            StepName = "Location",
                            StepNumber = 2,
                            StepTitle = "Location"
                        },
                        new
                        {
                            Id = new Guid("fa2827be-bb1e-453b-8295-d5daf2fd7616"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9580),
                            Description = "Your professional information",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 3,
                            Phase = 1,
                            StepName = "ProfessionalProfile",
                            StepNumber = 3,
                            StepTitle = "Professional Profile"
                        },
                        new
                        {
                            Id = new Guid("6f24c58a-7c99-4b02-84d6-6e7ba1cc7e11"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9583),
                            Description = "Select your skills",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 4,
                            Phase = 1,
                            StepName = "Skills",
                            StepNumber = 4,
                            StepTitle = "Skills"
                        },
                        new
                        {
                            Id = new Guid("e1afabde-4b4d-40ec-8459-5d2537f37319"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9586),
                            Description = "Choose your preference",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 5,
                            Phase = 1,
                            StepName = "Preferences",
                            StepNumber = 5,
                            StepTitle = "What do you want to do?"
                        },
                        new
                        {
                            Id = new Guid("95666fd1-99a9-4dfe-9f7a-b04ca50da151"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9588),
                            Description = "Verify your data is correct",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 6,
                            Phase = 1,
                            StepName = "Confirmation",
                            StepNumber = 6,
                            StepTitle = "Review and Confirm"
                        },
                        new
                        {
                            Id = new Guid("abae0ed8-916e-424d-9106-99c81a13a280"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9593),
                            Description = "Add your work experience",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 7,
                            Phase = 2,
                            StepName = "WorkExperience",
                            StepNumber = 7,
                            StepTitle = "Work Experience"
                        },
                        new
                        {
                            Id = new Guid("01729bca-2f02-4456-9255-33096fc4ce7c"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9595),
                            Description = "Add your education",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 8,
                            Phase = 2,
                            StepName = "Education",
                            StepNumber = 8,
                            StepTitle = "Education"
                        },
                        new
                        {
                            Id = new Guid("d1889f95-9982-4b55-8856-6d866ebeeb78"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9597),
                            Description = "Add your certifications",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 9,
                            Phase = 2,
                            StepName = "Certifications",
                            StepNumber = 9,
                            StepTitle = "Certifications"
                        },
                        new
                        {
                            Id = new Guid("2a45a283-794a-4ee7-8d5d-529d9a2e1431"),
                            CreatedAt = new DateTime(2026, 8, 12, 15, 48, 0, 827, DateTimeKind.Utc).AddTicks(9600),
                            Description = "Upload your CV/resume",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 10,
                            Phase = 2,
                            StepName = "UploadCV",
                            StepNumber = 10,
                            StepTitle = "Upload CV"
                        });
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTApplication", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTVacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("PT_VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("Candidate")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCandidate", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateCertification", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Certifications")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateEducation", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Educations")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateExperience", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Experiences")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateSkill", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTSkill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("PT_SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("Company")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCompany", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTempVacancy", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("TempVacancies")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancy", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCompany", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("PT_CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancySkill", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTSkill", "Skill")
                        .WithMany()
                        .HasForeignKey("PT_SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTVacancy", "Vacancy")
                        .WithMany("VacancySkills")
                        .HasForeignKey("PT_VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCRefreshToken", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserDevice", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserRole", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYUserPreference", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("OpenToWork.Models.Entities.SYUserPreference", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateSkills");

                    b.Navigation("Certifications");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTSkill", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancy", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("VacancySkills");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUser", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Company");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TempVacancies");

                    b.Navigation("UserDevices");

                    b.Navigation("UserPreference");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
