<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RequisitoSeeder extends Seeder
{
    public function run()
    {
        $requisitos = [
            // Obligatorios por defecto
            [
                'nombre'      => 'Cedula de identidad',
                'slug'        => 'cedula-identidad',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Antecedentes penales (Record de Policia)',
                'slug'        => 'antecedentes-penales',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Cotizaciones INSS',
                'slug'        => 'cotizaciones-inss',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Curriculum actualizado',
                'slug'        => 'cv-actualizado',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Referencias laborales',
                'slug'        => 'referencias-laborales',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Experiencia comprobable',
                'slug'        => 'experiencia-comprobable',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Titulo academico',
                'slug'        => 'titulo-academico',
                'tipo'        => 'obligatorio',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // Deseables por defecto
            [
                'nombre'      => 'Disponibilidad inmediata',
                'slug'        => 'disponibilidad-inmediata',
                'tipo'        => 'deseable',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Vehiculo propio',
                'slug'        => 'vehiculo-propio',
                'tipo'        => 'deseable',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Disponibilidad para viajar',
                'slug'        => 'disponibilidad-viajar',
                'tipo'        => 'deseable',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Licencia de conducir',
                'slug'        => 'licencia-conducir',
                'tipo'        => 'deseable',
                'es_default'  => true,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // No default - el usuario los busca y agrega
            [
                'nombre'      => 'Conocimiento en C#',
                'slug'        => 'conocimiento-csharp',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Conocimiento en PHP',
                'slug'        => 'conocimiento-php',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Conocimiento en Python',
                'slug'        => 'conocimiento-python',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Conocimiento en JavaScript',
                'slug'        => 'conocimiento-javascript',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Conocimiento en Java',
                'slug'        => 'conocimiento-java',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Manejo de Excel avanzado',
                'slug'        => 'excel-avanzado',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Manejo de paquetes contables',
                'slug'        => 'paquetes-contables',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Ingles conversacional',
                'slug'        => 'ingles-conversacional',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Trabajo bajo presion',
                'slug'        => 'trabajo-bajo-presion',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Liderazgo de equipos',
                'slug'        => 'liderazgo-equipos',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nombre'      => 'Certificacion tecnica',
                'slug'        => 'certificacion-tecnica',
                'tipo'        => 'deseable',
                'es_default'  => false,
                'estado'      => 'activo',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('cat_requisito')->insertBatch($requisitos);
    }
}
